# Generated by Django 4.2.27 on 2026-01-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('entrada_ts', models.DateTimeField(auto_now_add=True)),
                ('salida_ts', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('procesada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='registrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('propietario', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
