# Generated by Django 4.2.27 on 2026-01-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='entrada_ts',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registrada',
            name='propietario',
            field=models.CharField(max_length=100),
        ),
    ]
