# Generated by Django 4.2.27 on 2026-01-09 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_entrada_entrada_ts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='salida_ts',
            new_name='salida',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='entrada_ts',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='procesada',
        ),
        migrations.RemoveField(
            model_name='registrada',
            name='activo',
        ),
        migrations.AddField(
            model_name='entrada',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registrada',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
