# Generated by Django 4.2.27 on 2026-01-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_rename_salida_ts_entrada_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='procesada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='control.registrada'),
        ),
    ]
