# Generated by Django 4.2.27 on 2026-01-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_entrada_procesada_alter_entrada_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
