# Generated by Django 4.2.27 on 2026-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_entrada_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
