# Generated by Django 4.2.27 on 2026-01-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_entrada_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrada',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registrada',
            name='propietario',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
    ]
