# Generated by Django 4.2 on 2026-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_registrada_activo_alter_registrada_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='entrada',
            field=models.DateTimeField(),
        ),
    ]
